name: partgs_fix
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - python=3.8
  - pip=23.0.1
  - tqdm
  - psutil
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - torchvision=0.15.2
  - setuptools=69.1.1
  - mkl==2024.0
  - pandas
  - opencv

# 手动、在 torch 已存在的环境里编译 必须这个顺序
# pip install -e submodules/simple-knn
# pip install -e submodules/fused-ssim
# pip install -e submodules/diff-gaussian-rasterization