name: partgs_fix
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - plyfile
  - tqdm
  - psutil
  - pytorch::pytorch=2.1.0
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision=0.16.0
  - setuptools=69.1.1
  - mkl
  - numpy<2
  - pandas
  - opencv
  - matplotlib
  - wandb
  

# conda env create -f environment.yml -n partgs_fix
# conda activate partgs_fix
# pip install --no-build-isolation -e submodules/simple-knn
# pip install --no-build-isolation -e submodules/fused-ssim
# pip install --no-build-isolation -e submodules/diff-gaussian-rasterization